/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src/presentation/components",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      '../src/presentation/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET: { host: string; port: number } | undefined;
}

type StorybookGlobal = typeof globalThis & {
  view?: View;
  STORIES?: typeof normalizedStories;
  STORYBOOK_WEBSOCKET?: { host: string; port: number };
};

const g = globalThis as StorybookGlobal;

const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

g.STORIES = normalizedStories;


// @ts-ignore
module?.hot?.accept?.();



if (!g.view) {
  g.view = start({
    annotations,
    storyEntries: normalizedStories,

  });
} else {
  updateView(g.view, annotations, normalizedStories);
}

export const view: View = g.view;
