# Generated by husky
# https://github.com/typicode/husky?WT_tt_campaign=unknown21&tt_from=gh_personal_token&utm_source=github&utm_medium=referral&utm_content=unknown21

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Workaround for some CI systems that don't support POSIX sh
if [ -z "${HUSKY-}" ]; then
  export HUSKY=0
fi

# Skip if HUSKY=0 (not used for commit-msg hook)
if [ "${HUSKY}" != "0" ]; then
  command_exists git || { echo >&2 "git command not found"; exit 1; }
  command_exists pnpm || { echo >&2 "pnpm command not found"; exit 1; }
fi

# Skip if CI=true
if [ "${CI}" = "true" ]; then
  exit 0
fi

cd "$(dirname "$0")/.." && pnpm pre-commit
